# --- !Ups

create table "COMPANY" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL);
create table "COMPUTER" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL,"INTRODUCED" BIGINT,"DISCONTINUED" BIGINT,"COMPANY_ID" BIGINT);

# --- !Downs

drop table "COMPUTER";
drop table "COMPANY";

